# Generated by Django 3.0.5 on 2020-04-17 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0002_remove_division_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='division',
            name='state',
            field=models.CharField(default='', max_length=2),
            preserve_default=False,
        ),
    ]
