name: Colorado
os-id-prefix: "ocd-division/country:us/state:co"
id-mappings:
  # CO TIGER_RD18 files are split between whole_block and split_block versions
  # so some override must take place as expected/generated zip URL does not exist
  sldl:
    key: DISTRICT
    sld-match: 'sldl-080([\d]+)'
    url: https://www2.census.gov/geo/tiger/TIGER_RD18/STATE/08_COLORADO/08/tl_rd22_08_sldl_whole_block.zip
  sldu:
    key: DISTRICT
    sld-match: 'sldu-080([\d]+)'
    url: https://www2.census.gov/geo/tiger/TIGER_RD18/STATE/08_COLORADO/08/tl_rd22_08_sldu_whole_block.zip
  cd:
    key: DISTRICT
    sld-match: 'cd-080(\d)'
    url: https://www2.census.gov/geo/tiger/TIGER_RD18/STATE/08_COLORADO/08/tl_rd22_08_cd118_whole_block.zip
