name: North Dakota
os-id-prefix: "ocd-division/country:us/state:nd"
id-mappings:
  # ND TIGER_RD18 SLDU/SLDL files are split between whole_block and split_block versions
  sldl:
    key: DISTRICT
    sld-match: 'sldl-380(\d+[A-Z]?)'
    url: https://www2.census.gov/geo/tiger/TIGER_RD18/STATE/38_NORTH_DAKOTA/38/tl_rd22_38_sldl_whole_block.zip
  sldu:
    key: DISTRICT
    sld-match: 'sldu-380([\d]+)'
    url: https://www2.census.gov/geo/tiger/TIGER_RD18/STATE/38_NORTH_DAKOTA/38/tl_rd22_38_sldu_whole_block.zip
  cd:
    key: DISTRICT
    sld-match: 'cd-380(\d)'
