name: Pennsylvania
os-id-prefix: "ocd-division/country:us/state:pa"
id-mappings:
  # PA TIGER_RD18 SLDL files are split between whole_block and split_block versions
  sldl:
    key: DISTRICT
    sld-match: 'sldl-42([\d]+)'
    url: https://www2.census.gov/geo/tiger/TIGER_RD18/STATE/42_PENNSYLVANIA/42/tl_rd22_42_sldl_whole_block.zip
  sldu:
    key: DISTRICT
    sld-match: 'sldu-420([\d]+)'
  cd:
    key: DISTRICT
    sld-match: 'cd-42([\d]+)'
