name: Virginia
os-id-prefix: "ocd-division/country:us/state:va"
id-mappings:
  sldl:
    key: DISTRICT
    sld-match: 'sldl-51([\d]+)'
  sldu:
    key: DISTRICT
    sld-match: 'sldu-51(\d+)'
    url: https://www2.census.gov/geo/tiger/TIGER2023/SLDU/tl_2023_51_sldu.zip
  cd:
    key: DISTRICT
    sld-match: 'cd-51([\d]+)'
