name: Washington
os-id-prefix: "ocd-division/country:us/state:wa"
id-mappings:
  # TIGER2024 files are up to date with maps effective 1/13/25
  sldl:
    key: DISTRICT
    sld-match: 'sldl-530(\d+)'
    url: 'https://www2.census.gov/geo/tiger/TIGER2024/SLDL/tl_2024_53_sldl.zip'
  sldu:
    key: DISTRICT
    sld-match: 'sldu-53(\d+)'
    url: 'https://www2.census.gov/geo/tiger/TIGER2024/SLDU/tl_2024_53_sldu.zip'
  cd:
    key: DISTRICT
    sld-match: 'cd-53(\d+)'
