name: Wisconsin
os-id-prefix: "ocd-division/country:us/state:wi"
id-mappings:
  # TIGER2024 files are up to date with maps effective 1/6/25
  sldl:
    key: DISTRICT
    sld-match: 'sldl-55([\d]+)'
    url: 'https://www2.census.gov/geo/tiger/TIGER2024/SLDL/tl_2024_55_sldl.zip'
  sldu:
    key: DISTRICT
    sld-match: 'sldu-550([\d]+)'
    url: 'https://www2.census.gov/geo/tiger/TIGER2024/SLDU/tl_2024_55_sldu.zip'
  cd:
    key: DISTRICT
    sld-match: 'cd-550(\d)'
