name: Lint Files

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: setup Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"
    - name: install Poetry
      uses: snok/install-poetry@v1.3.3
    - name: install dependencies
      run: poetry install --no-root
    - name: flake8 check
      run: poetry run flake8 .
    - name: black check
      run: poetry run black --check --diff .
    - name: Yaml file linting
      run: |
        docker run --rm \
        -v $(pwd):/code \
        registry.gitlab.com/pipeline-components/yamllint:latest -s .
